version: "3.7"

services:
    flask:
        build: ./flask
        container_name: flask
        restart: always
        volumes:
            # change `~/journals` to the location of your `journals` folder
            # same for `stories` and `ideas`
            - ~/journals:/usr/share/journals
            - ~/stories:/usr/share/stories
            - ~/ideas:/usr/share/ideas
            # Consider changing this to /var/log/uwsgi:/var/log/uwsgi in production
            - ./log/uwsgi:/var/log/uwsgi
        expose:
            - 8080

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            # the first `80` is the host port number
            # change it if port `80` is in use by another application
            - "80:80"
        volumes:
            # Consider changing this to /var/log/nginx:/var/log/nginx in production
            - ./log/nginx:/var/log/nginx
