version: "3.7"

services:
    flask:
        build: ./flask
        container_name: flask
        restart: always
        environment:
            - JOURNAL_DIR=/usr/share/journals
        volumes:
            - ./test_files:/usr/share/journals
            - ./log/uwsgi:/var/log/uwsgi
        expose:
            - 8080

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "5000:80"
        volumes:
            - ./log/nginx:/var/log/nginx
